Nod 642 storicizzare i dati presenti da piu di 30 giorni
pagopa/pagopa-fdr pull request #53
Opened 2024-01-23 11:19 UTC by andrea-barchi

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as
  expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-01-25 09:30 UTC, mscattarella approved these changes

2024-01-25 09:58 UTC, aomegax requested changes

2024-01-25 09:58 UTC, aomegax commented on helm/values-dev.yaml
> +      BLOB_HISTORY_CONNECTION_STRING: "fdr-history-sa-connection-string"
use the same key, like `FDR_HISTORY_CONNECTION_STRING` instead of `BLOB_HISTORY_CONNECTION_STRING` and `TABLE_HISTORY_CONNECTION_STRING`

2024-01-26 11:25 UTC, aomegax approved these changes

2024-01-26 11:25 UTC, merged